notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4f71b9fa80e108068016
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
dist: trusty
cache:
  directories:
  - $HOME/.opam
  - $HOME/.ccache
  - $HOME/build/pirapira/cpp-ethereum
  - $HOME/build/pirapira/cmake
env:
  global:
  - CASHER_TIME_OUT=1200
sudo: required
before_install:
- BAMBOO=`pwd`
- sudo apt-get -qq update
- sudo apt-get install aspcud ccache
# - git clone https://github.com/polyml/polyml.git
# - cd polyml
# - git checkout v5.6
# - ./configure
# - make
# - make compiler
# - sudo make install
# - cd -
# - sudo updatedb
# - locate libpolymain.a
- wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sudo sh -s /usr/local/bin
- export OPAMJOBS=2
- opam init -y --comp=4.04.2
- opam switch 4.04.2
- eval `opam config env`
- opam update
- opam upgrade -y
- opam install -y ocamlfind menhir batteries rope zarith ppx_deriving rpc=2.0.0 cryptokit hex
- cd ../..
- if [ ! -d cpp-ethereum/.git ]; then rm -rf cpp-ethereum; git clone https://github.com/ethereum/cpp-ethereum --recursive; fi
- sudo apt install -y build-essential libgmp-dev libleveldb-dev libmicrohttpd-dev
- sudo apt purge -y cmake
- mkdir -p cmake
- cd cmake
- if [ ! -f cmake-3.8.2-Linux-x86_64.tar.gz ]; then wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz && tar xf cmake-3.8.2-Linux-x86_64.tar.gz; fi
- PATH=`pwd`/cmake-3.8.2-Linux-x86_64/bin:$PATH
- cd -
- cmake --version
- cd cpp-ethereum
- git fetch
- git checkout origin/test-raw-sign
- git show | head -n 3
- git submodule update --recursive
- mkdir -p build
- cd build
- cmake ..
- make -j3 eth
- sudo make install
- cd $BAMBOO
- sudo apt install texlive-latex-base texlive-science texlive-math-extra
script:
- make doc/spec.pdf
- make
- make test
- make endToEnd
- which eth
- eth --version
- mkdir -p /tmp/test
- eth --test -d /tmp/test &> eth.log &
- PID=$!
- sleep 4
- ./endToEnd.native
- kill $PID
- cat eth.log
