(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*         ------------------------------------------                                                                                           *)
(*              sgm*pi           sgm                                                                                                            *)
(*              x : Addr   |-  cn : Addr                                                                                                        *)
(*           -----------------------------------------                                                                                          *)
(*                    pi       sgm  pi                                  sgm'                                                                    *)
(*              |-  \x:Addr.cn  : (x:Addr)->Addr               |- myaddr : Addr                                                                 *)
(*            ----------------------------------------------------------------------------------------                                          *)
(*                                  pi              sgm                                                                                         *)
(*                            |- (\x:Addr.cn) myaddr : Addr                                                                                     *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*            -------------------------------------------                                                                                       *)
(*               the function has the reentrance guard                                                                                          *)
(*           --------------------------------------------------                                                                                 *)
(*               the function must be used once                                                                                                 *)
(*         ------------------------------------------                                                                                           *)
(*              sgm*1            sgm                                                                                                            *)
(*              x : Addr   |-  cn : Addr                                                                                                        *)
(*           -----------------------------------------                                                                                          *)
(*                    1        sgm  1                                   sgm'                                                                    *)
(*              |-  \x:Addr.cn  : (x:Addr)->Addr               |- myaddr : Addr                                                                 *)
(*            ----------------------------------------------------------------------------------------                                          *)
(*                                  1               sgm                                                                                         *)
(*                            |- (\x:Addr.cn) myaddr : Addr                                                                                     *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(* contract WalletLibrary {                                                                                                                     *)
(*      address owner;                                                                                                                          *)
(*                                                                                                                                              *)
(*      // called by constructor                                                                                                                *)
(*      fun{1} initWallet(address _owner) {                                                                                                     *)
(*          owner = _owner;                                                                                                                     *)
(*          // ... more setup ...                                                                                                               *)
(*      }                                                                                                                                       *)
(*                                                                                                                                              *)
(*      fun{2} changeOwner(address _new_owner) external {  // we can use this function only twice                                               *)
(*          if (msg.sender == owner) {                                                                                                          *)
(*              owner = _new_owner;                                                                                                             *)
(*          }                                                                                                                                   *)
(*      }                                                                                                                                       *)
(*                                                                                                                                              *)
(*      function () payable {                                                                                                                   *)
(*          // ... receive money, log events, ...                                                                                               *)
(*      }                                                                                                                                       *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(* contract WalletLibrary {                                                                                                                     *)
(*      address owner;                                                                                                                          *)
(*                                                                                                                                              *)
(*      // called by constructor                                                                                                                *)
(*      function initWallet(address _owner) {                                                                                                   *)
(*          owner = _owner;                                                                                                                     *)
(*          // ... more setup ...                                                                                                               *)
(*      }                                                                                                                                       *)
(*                                                                                                                                              *)
(*      function changeOwner(address _new_owner) external {                                                                                     *)
(*          if (msg.sender == owner) {                                                                                                          *)
(*              owner = _new_owner;                                                                                                             *)
(*          }                                                                                                                                   *)
(*      }                                                                                                                                       *)
(*                                                                                                                                              *)
(*      function () payable {                                                                                                                   *)
(*          // ... receive money, log events, ...                                                                                               *)
(*      }                                                                                                                                       *)
(*                                                                                                                                              *)
(*      function withdraw(uint amount) external returns (bool success) {                                                                        *)
(*          if (msg.sender == owner) {                                                                                                          *)
(*              return owner.send(amount);                                                                                                      *)
(*          } else {                                                                                                                            *)
(*              return false;                                                                                                                   *)
(*          }                                                                                                                                   *)
(*      }                                                                                                                                       *)
(* }                                                                                                                                            *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                        -------------------------------------------                                                                           *)
(*                                  |-  create myaddr :  Addr                                                                                   *)
(*                               ---------------------------------------------- zeta                                                            *)
(*                                    |- let a  = myaddr in create a : Addr                                                                     *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
(*                                                                                                                                              *)
